title = "Skandan Chandrasekar"
baseURL = "https://skandanc.me"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
email = "skandan68@gmail.com"
favicon = "/favicon.ico"
firstName = "Skandan"
lastName = "Chandrasekar"
profileImage = "img/avatar.jpg"
showEducation = true
showExperience = true
showOpenSource = true
showProjects = true
showPublications = true
showQr = true
showSkills = true

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://github.com/SkandanC/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"